spring:
  datasource:
#    url: ${JDBC_DATABASE_URL}
#    username: ${JDBC_DATABASE_USERNAME}
#    password: ${JDBC_DATABASE_PASSWORD}
    url: jdbc:mysql://localhost:3306/abfm_test?useSSL=false&characterEncoding=utf8
    username: abfm
    password: abfm
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false

